<?xml version="1.0" encoding="utf-8"?><Database Name="ingram_ctr_db" Class="ingram_ctrDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\ingram_ctr_db.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ingram_ctr_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Counter" Member="tbl_Counters">
    <Type Name="tbl_Counter">
      <Column Name="ctr_value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>